name: Compile Pico Firmware

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Logic Analyzer Code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 1

      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: 'true'
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Build Firmware
        env:
          PICO_SDK_PATH: ${{ github.workspace }}/pico-sdk
        run: |
          cd Firmware
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logic-analyzer-firmware
          path: |
            Firmware/build/*.uf2
