name: Compile Pico Firmware

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

      - name: Setup Pico SDK
        run: |
          git clone --depth 1 https://github.com
          cd pico-sdk
          git submodule update --init --depth 1
          echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Build Firmware
        run: |
          cd Firmware
          mkdir build
          cd build
          # Utilisation de -DSDK_FETCH_DEPS=TRUE au cas où le SDK aurait besoin d'autres modules
          cmake ..
          make -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logic-analyzer-firmware
          path: Firmware/build/*.uf2
